() => [
  {
    group: 'car',
    name: 'corolla',
    title: 'Toyota Corolla',
    stars: 2,
    price: 950,
    priceGroup: ['cheap'],
    equip: ['gearbox', 'climat'],
  },
  {
    group: 'car',
    name: '4x4',
    title: 'Lada 4x4',
    stars: 1,
    price: 550,
    priceGroup: ['suv'],
    equip: ['tires'],
  },
  {
    group: 'car',
    name: 'jetta',
    title: 'Volkswagen Jetta',
    stars: 2,
    price: 800,
    priceGroup: ['family'],
    equip: ['climat'],
  },
  {
    group: 'car',
    name: 'vitara',
    title: 'Suzuki Vitara',
    stars: 2,
    price: 1100,
    priceGroup: ['family'],
    equip: ['gearbox', 'climat'],
  },
  {
    group: 'car',
    name: 'cla',
    title: 'Mercedes-Benz CLA',
    stars: 4,
    price: 2250,
    priceGroup: ['vip'],
    equip: ['start', 'climat', 'wheels', 'leather'],
  },
  {
    group: 'car',
    name: 'corolla',
    title: 'Toyota Corolla',
    stars: 2,
    price: 950,
    priceGroup: ['cheap'],
    equip: ['gearbox', 'climat'],
  },
  {
    group: 'car',
    name: '4x4',
    title: 'Lada 4x4',
    stars: 1,
    price: 550,
    priceGroup: ['suv'],
    equip: ['tires'],
  },
  {
    group: 'car',
    name: 'jetta',
    title: 'Volkswagen Jetta',
    stars: 2,
    price: 800,
    priceGroup: ['family'],
    equip: ['climat'],
  },
  {
    group: 'car',
    name: 'vitara',
    title: 'Suzuki Vitara',
    stars: 2,
    price: 1100,
    priceGroup: ['family'],
    equip: ['gearbox', 'climat'],
  },
  {
    group: 'car',
    name: 'cla',
    title: 'Mercedes-Benz CLA',
    stars: 4,
    price: 2250,
    priceGroup: ['vip'],
    equip: ['start', 'climat', 'wheels', 'leather'],
  },
  {
    group: 'car',
    name: 'corolla',
    title: 'Toyota Corolla',
    stars: 2,
    price: 950,
    priceGroup: ['cheap'],
    equip: ['gearbox', 'climat'],
  },
  {
    group: 'car',
    name: '4x4',
    title: 'Lada 4x4',
    stars: 1,
    price: 550,
    priceGroup: ['suv'],
    equip: ['tires'],
  },
  {
    group: 'car',
    name: 'jetta',
    title: 'Volkswagen Jetta',
    stars: 2,
    price: 800,
    priceGroup: ['family'],
    equip: ['climat'],
  },
  {
    group: 'car',
    name: 'vitara',
    title: 'Suzuki Vitara',
    stars: 2,
    price: 1100,
    priceGroup: ['family'],
    equip: ['gearbox', 'climat'],
  },
  {
    group: 'car',
    name: 'cla',
    title: 'Mercedes-Benz CLA',
    stars: 4,
    price: 2250,
    priceGroup: ['vip'],
    equip: ['start', 'climat', 'wheels', 'leather'],
  },

  { group: 'service', name: 'gearbox', title: 'Коробка автомат', price: '+20%', stars: 1, equip: ['gearbox'] },
  { group: 'service', name: 'gearbox', title: 'Коробка автомат', price: '+20%', stars: 1, equip: ['gearbox'] },
  { group: 'service', name: 'ins20', title: 'Страховка авто', price: '+20%' },
  { group: 'service', name: 'ins20', title: 'Страховка авто', price: '+20%' },
  { group: 'service', name: 'ins30', title: 'Страховка жизни', price: '+30%' },
  { group: 'service', name: 'ins30', title: 'Страховка жизни', price: '+30%' },
  { group: 'service', name: 'wheels', title: 'Литые диски', price: '+10%', equip: ['wheels'] },
  { group: 'service', name: 'wheels', title: 'Литые диски', price: '+10%', equip: ['wheels'] },
  { group: 'service', name: 'wheels', title: 'Литые диски', price: '+10%', equip: ['wheels'] },
  { group: 'service', name: 'wheels', title: 'Литые диски', price: '+10%', equip: ['wheels'] },
  { group: 'service', name: 'tires', title: 'Зимняя резина', price: '+10%', priceGroup: ['suv'], equip: ['tires'] },
  { group: 'service', name: 'tires', title: 'Зимняя резина', price: '+10%', priceGroup: ['suv'], equip: ['tires'] },
  { group: 'service', name: 'tires', title: 'Зимняя резина', price: '+10%', priceGroup: ['suv'], equip: ['tires'] },
  { group: 'service', name: 'tires', title: 'Зимняя резина', price: '+10%', priceGroup: ['suv'], equip: ['tires'] },
  { group: 'service', name: 'sport', title: 'Спортивные обвесы', price: '+10%', priceGroup: ['cheap'] },
  { group: 'service', name: 'sport', title: 'Спортивные обвесы', price: '+10%', priceGroup: ['cheap'] },
  { group: 'service', name: 'aerograf', title: 'Аэрография', price: '+250', priceGroup: ['vip', 'woman'] },
  { group: 'service', name: 'vinyl', title: 'Виниловая пленка', price: '+100', priceGroup: ['vip', 'woman'] },
  { group: 'service', name: 'start', title: 'Пуск двигателя кнопкой', price: '+100', stars: 1, equip: ['start'] },
  { group: 'service', name: 'start', title: 'Пуск двигателя кнопкой', price: '+100', stars: 1, equip: ['start'] },
  {
    group: 'service',
    name: 'climat',
    title: 'Климат-контроль',
    price: '+20%',
    priceGroup: ['family'],
    equip: ['climat'],
  },
  {
    group: 'service',
    name: 'climat',
    title: 'Климат-контроль',
    price: '+20%',
    priceGroup: ['family'],
    equip: ['climat'],
  },
  { group: 'service', name: 'leather', title: 'Кожаный салон', price: '+10%', stars: 1, equip: ['leather'] },
  { group: 'service', name: 'leather', title: 'Кожаный салон', price: '+10%', stars: 1, equip: ['leather'] },
  { group: 'service', name: 'multisystem100', title: 'Мультимедиа система', price: '+100' },
  { group: 'service', name: 'multisystem200', title: 'Мультимедиа система', price: '+200' },
  { group: 'service', name: 'signaling50', title: 'Автосигнализация', price: '+50' },
  { group: 'service', name: 'signaling100', title: 'Автосигнализация', price: '+100' },
  { group: 'service', name: 'anticor', title: 'Антикоррозийная обработка кузова', price: '+50' },
  { group: 'service', name: 'anticor', title: 'Антикоррозийная обработка кузова', price: '+50' },
  { group: 'service', name: 'anticor', title: 'Антикоррозийная обработка кузова', price: '+50' },
  { group: 'service', name: 'anticor', title: 'Антикоррозийная обработка кузова', price: '+50' },

  { group: 'client', name: 'pensioner', title: 'Пенсионер', money: 600, stars: 1, priceGroup: '*' },
  { group: 'client', name: 'programmer', title: 'Программист', money: 1200, stars: 2, priceGroup: '*' },
  { group: 'client', name: 'taxi', title: 'Таксист', money: 500, stars: 1, priceGroup: '*' },
  { group: 'client', name: 'topmanager', title: 'Топ-менеджер', money: 2200, stars: 4, priceGroup: ['vip'] },
  { group: 'client', name: 'deputy', title: 'Помощник депутата', money: 2100, stars: 3, priceGroup: ['vip'] },
  { group: 'client', name: 'businesswoman', title: 'Бизнес-леди', money: 2000, stars: 4, priceGroup: ['vip', 'woman'] },
  { group: 'client', name: 'family1', title: 'Семейная пара', money: 1100, stars: 2, priceGroup: ['family'] },
  { group: 'client', name: 'family2', title: 'Семейная пара', money: 1200, stars: 2, priceGroup: ['family'] },
  { group: 'client', name: 'fisherman', title: 'Любитель рыбалки', money: 900, stars: 2, priceGroup: ['suv'] },
  { group: 'client', name: 'blonde', title: 'Блондинка', money: 1500, stars: 3, priceGroup: ['woman'] },
  { group: 'client', name: 'hunter', title: 'Любитель охоты', money: 1800, stars: 3, priceGroup: ['suv', 'vip'] },
  { group: 'client', name: 'farmer', title: 'Фермер', money: 1000, stars: 1, priceGroup: ['suv', 'family'] },
  { group: 'client', name: 'newlyweds1', title: 'Молодожены', money: 800, stars: 1, priceGroup: ['cheap', 'family'] },
  { group: 'client', name: 'newlyweds2', title: 'Молодожены', money: 900, stars: 2, priceGroup: ['cheap', 'family'] },
  { group: 'client', name: 'blogger', title: 'Блогер', money: 1300, stars: 3, priceGroup: '*' },
  { group: 'client', name: 'major', title: 'Мажор', money: 1500, stars: 2, priceGroup: ['cheap', 'vip'] },

  { group: 'feature', name: 'for_work', title: 'Покупает для работы', replaceClient: true },
  { group: 'feature', name: 'for_present', title: 'Покупает в подарок', replaceClient: true },
  { group: 'feature', name: 'present', title: 'Пообещали подарок'},
  { group: 'feature', name: 'reference1', title: 'Привел друга', reference: true},
  { group: 'feature', name: 'reference2', title: 'Привел друга', reference: true},
  { group: 'feature', name: 'problem1', title: 'Проблемный клиент'},
  { group: 'feature', name: 'problem2', title: 'Проблемный клиент'},
  { group: 'feature', name: 'downer', title: 'Зануда'},
  { group: 'feature', name: 'grandmother', title: 'Помогла бабушка', money: '+200', target: 'client' },
  { group: 'feature', name: 'relatives', title: 'Помогли родственники', money: '+100', target: 'client' },
  { group: 'feature', name: 'friends250', title: 'Занял у друзей', money: '+250', target: 'client' },
  { group: 'feature', name: 'tradein300', title: 'TRADE-IN', price: '-300', target: 'car' },
  { group: 'feature', name: 'tradein400', title: 'TRADE-IN', price: '-400', target: 'car' },
  { group: 'feature', name: 'tradein500', title: 'TRADE-IN', price: '-500', target: 'car' },
  { group: 'feature', name: 'parents', title: 'Помогли родители', money: '+300', target: 'client' },
  { group: 'feature', name: 'friends150', title: 'Добавили друзья', money: '+150', target: 'client' },
  { group: 'feature', name: 'promo', title: 'По акции', price: '-10%', target: 'car' },
  { group: 'feature', name: 'testdrive', title: 'Авто с тест-драйва', price: '-20%', target: 'car' },
  { group: 'feature', name: 'vip20', title: 'Постоянный клиент', price: '-20%', target: 'car' },
  { group: 'feature', name: 'vip10', title: 'Постоянный клиент', price: '-10%', target: 'car' },
  { group: 'feature', name: 'contact', title: 'Связи в салоне', price: '-20%', target: 'car' },
  { group: 'feature', name: 'grant400', title: 'Субсидия', price: '-400', target: 'car' },
  { group: 'feature', name: 'grant500', title: 'Субсидия', price: '-500', target: 'car' },
  { group: 'feature', name: 'grant600', title: 'Субсидия', price: '-600', target: 'car' },

  { group: 'credit', name: 'credit100', title: 'Взял кредит', money: '+100%' },
  { group: 'credit', name: 'credit150', title: 'Взял кредит', money: '+150%' },
  { group: 'credit', name: 'credit200', title: 'Взял кредит', money: '+200%' },
];
